name: CI/CD Pipeline

on:
  push:

jobs:
  cypress-run:
    runs-on: windows-latest
    strategy:
      matrix:
        folder: [ "auth", "accounts", "transactions" ]  # Add folder names here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests in parallel
        run: |
          npx cypress run --record --key YOUR_CYPRESS_RECORD_KEY --parallel --spec "cypress/e2e/${{ matrix.folder }}/**/*.js"

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
